/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## Git Drive 接口文档

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */
import type { JsonResultTypeTokenStringMeUser } from './jsonResultTypeTokenStringMeUser';

/**
 * 控制器方法返回类型的通用别名
用于简化 Promise<JsonResultType<T>> 的写法
 */
export type ApiResponseTokenStringMeUser = JsonResultTypeTokenStringMeUser;
