/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## Git Drive 接口文档

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */
import type { PickPrismaFavoriteCreateInputExcludeKeyofPrismaFavoriteCreateInputUid } from './pickPrismaFavoriteCreateInputExcludeKeyofPrismaFavoriteCreateInputUid';

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitPrismaFavoriteCreateInputUid = PickPrismaFavoriteCreateInputExcludeKeyofPrismaFavoriteCreateInputUid;
