/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## Git Drive 接口文档

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */
import type { PrismaUserUpdateInputSalt } from './prismaUserUpdateInputSalt';
import type { PrismaUserUpdateInputAvatar } from './prismaUserUpdateInputAvatar';
import type { PrismaUserUpdateInputNickname } from './prismaUserUpdateInputNickname';
import type { PrismaUserUpdateInputDes } from './prismaUserUpdateInputDes';
import type { PrismaUserUpdateInputUsername } from './prismaUserUpdateInputUsername';
import type { PrismaUserUpdateInputRole } from './prismaUserUpdateInputRole';
import type { PrismaUserUpdateInputPassword } from './prismaUserUpdateInputPassword';
import type { PrismaUserUpdateInputEmail } from './prismaUserUpdateInputEmail';

export interface PrismaUserUpdateInput {
  /** @nullable */
  salt?: PrismaUserUpdateInputSalt;
  /** @nullable */
  avatar?: PrismaUserUpdateInputAvatar;
  /** @nullable */
  nickname?: PrismaUserUpdateInputNickname;
  /** @nullable */
  des?: PrismaUserUpdateInputDes;
  /** @nullable */
  username?: PrismaUserUpdateInputUsername;
  /** @nullable */
  role?: PrismaUserUpdateInputRole;
  /** @nullable */
  password?: PrismaUserUpdateInputPassword;
  email?: PrismaUserUpdateInputEmail;
}
