/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## Git Drive 接口文档

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */
import type { PrismaRepoUpdateInputRname } from './prismaRepoUpdateInputRname';
import type { PrismaRepoUpdateInputUid } from './prismaRepoUpdateInputUid';
import type { PrismaRepoUpdateInputId } from './prismaRepoUpdateInputId';

export interface PrismaRepoUpdateInput {
  /** @nullable */
  rname?: PrismaRepoUpdateInputRname;
  uid?: PrismaRepoUpdateInputUid;
  id?: PrismaRepoUpdateInputId;
}
