/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## Git Drive 接口文档

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */

export type RootResetPwdBody = {
  code: string;
  email: string;
  aseKeyEncrypt: string;
  password: string;
};
