/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## Git Drive 接口文档

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */
import type {
  JsonResultTypeFavorite,
  JsonResultTypeFavoriteArray,
  PickPrismaFavoriteCreateInputExcludeKeyofPrismaFavoriteCreateInputUid
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * 获取所有仓库信息
 * @summary 列表
 */
export const getList = (
    
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeFavoriteArray>(
      {url: `/api/favorite/list`, method: 'GET'
    },
      options);
    }
  /**
 * 新增收藏
 * @summary 创建
 */
export const create = (
    pickPrismaFavoriteCreateInputExcludeKeyofPrismaFavoriteCreateInputUid: PickPrismaFavoriteCreateInputExcludeKeyofPrismaFavoriteCreateInputUid,
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeFavorite>(
      {url: `/api/favorite`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pickPrismaFavoriteCreateInputExcludeKeyofPrismaFavoriteCreateInputUid
    },
      options);
    }
  export type GetListResult = NonNullable<Awaited<ReturnType<typeof getList>>>
export type CreateResult = NonNullable<Awaited<ReturnType<typeof create>>>
