/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## Git Drive 接口文档

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */
import type {
  JsonResultTypeUser,
  PrismaUserUpdateInput
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary 获取
 */
export const get = (
    
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeUser>(
      {url: `/api/me`, method: 'GET'
    },
      options);
    }
  /**
 * @summary 更新
 */
export const update = (
    prismaUserUpdateInput: PrismaUserUpdateInput,
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeUser>(
      {url: `/api/me`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: prismaUserUpdateInput
    },
      options);
    }
  export type Get = NonNullable<Awaited<ReturnType<typeof get>>>
export type Update = NonNullable<Awaited<ReturnType<typeof update>>>
