/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## Git Drive 接口文档

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetInfoRequest,
  JsonResultTypeAny,
  JsonResultTypeRepo,
  JsonResultTypeRepoOrDirOrFileArray,
  PrismaRepoUpdateInput,
  RepoAddFolderBody,
  RepoGetParams,
  RepoRemoveParams,
  RepoRenameBody,
  RepoUploadFileBody
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getInfo = (
    getInfoRequest: GetInfoRequest,
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeAny>(
      {url: `/api/repo/info`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getInfoRequest
    },
      options);
    }
  /**
 * 获取所有仓库信息
 * @summary 列表
 */
export const getList = (
    
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeRepoOrDirOrFileArray>(
      {url: `/api/repo/list`, method: 'GET'
    },
      options);
    }
  /**
 * 新增仓库
 * @summary 创建
 */
export const create = (
    prismaRepoUpdateInput: PrismaRepoUpdateInput,
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeRepo>(
      {url: `/api/repo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: prismaRepoUpdateInput
    },
      options);
    }
  /**
 * 不单可以删除仓库，还支持删除文件夹、文件
 * @summary 删除
 */
export const remove = (
    params: RepoRemoveParams,
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeRepo>(
      {url: `/api/repo`, method: 'DELETE',
        params
    },
      options);
    }
  /**
 * 获取仓库信息
 * @summary 查询
 */
export const get = (
    params: RepoGetParams,
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeRepoOrDirOrFileArray>(
      {url: `/api/repo`, method: 'GET',
        params
    },
      options);
    }
  /**
 * 创建文件夹到 repo 中
 * @summary 创建文件夹
 */
export const addFolder = (
    repoAddFolderBody: RepoAddFolderBody,
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeAny>(
      {url: `/api/repo/add-folder`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: repoAddFolderBody
    },
      options);
    }
  /**
 * 上传文件到 repo 中
 * @summary 上传文件
 */
export const uploadFile = (
    repoUploadFileBody: RepoUploadFileBody,
 options?: SecondParameter<typeof customAxiosInstance>,) => {const formData = new FormData();
formData.append(`path`, repoUploadFileBody.path)
formData.append(`repo`, repoUploadFileBody.repo)
formData.append(`file`, repoUploadFileBody.file)

      return customAxiosInstance<JsonResultTypeAny>(
      {url: `/api/repo/upload-file`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  /**
 * 上传文件到 repo 中
 * @summary 上传文件
 */
export const rename = (
    repoRenameBody: RepoRenameBody,
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeAny>(
      {url: `/api/repo/rename`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: repoRenameBody
    },
      options);
    }
  export type GetInfoResult = NonNullable<Awaited<ReturnType<typeof getInfo>>>
export type GetListResult = NonNullable<Awaited<ReturnType<typeof getList>>>
export type CreateResult = NonNullable<Awaited<ReturnType<typeof create>>>
export type RemoveResult = NonNullable<Awaited<ReturnType<typeof remove>>>
export type GetResult = NonNullable<Awaited<ReturnType<typeof get>>>
export type AddFolderResult = NonNullable<Awaited<ReturnType<typeof addFolder>>>
export type UploadFileResult = NonNullable<Awaited<ReturnType<typeof uploadFile>>>
export type RenameResult = NonNullable<Awaited<ReturnType<typeof rename>>>
