/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## Git Drive 接口文档

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */
import type {
  JsonResultTypeUser,
  UserGetParams
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary 获取
 */
export const get = (
    params: UserGetParams,
 options?: SecondParameter<typeof customAxiosInstance>,) => {
      return customAxiosInstance<JsonResultTypeUser>(
      {url: `/api/user`, method: 'GET',
        params
    },
      options);
    }
  export type GetResult = NonNullable<Awaited<ReturnType<typeof get>>>
