/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 1.0.0
 */
import type { JsonResultTypeTokenStringMeUser } from './jsonResultTypeTokenStringMeUser';

/**
 * 控制器方法返回类型的通用别名
用于简化 Promise<JsonResultType<T>> 的写法
 */
export type ApiResponseTokenStringMeUser = JsonResultTypeTokenStringMeUser;
