/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 1.0.0
 */

export interface DefaultSelectionPrisma36UserPayload {
  avatar: string;
  nickname: string;
  des: string;
  username: string;
  role: string;
  qq: number;
  password: string;
  email: string;
  id: number;
}
