/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## xx服务

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */

export interface DefaultSelectionPrisma36UserPayload {
  avatar: string;
  nickname: string;
  des: string;
  username: string;
  role: string;
  password: string;
  email: string;
  id: number;
}
