/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## Git Drive 接口文档

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */

export * from './apiResponse';
export * from './apiResponseAny';
export * from './apiResponseRepo';
export * from './apiResponseTokenStringMeUser';
export * from './apiResponseUser';
export * from './defaultSelectionPrisma36RepoPayload';
export * from './defaultSelectionPrisma36UserPayload';
export * from './jsonResultTypeAny';
export * from './jsonResultTypeRepo';
export * from './jsonResultTypeTokenStringMeUser';
export * from './jsonResultTypeTokenStringMeUserData';
export * from './jsonResultTypeUser';
export * from './loginParams';
export * from './prismaNullableStringFieldUpdateOperationsInput';
export * from './prismaRepoCreateInput';
export * from './prismaStringFieldUpdateOperationsInput';
export * from './prismaUserUpdateInput';
export * from './prismaUserUpdateInputAvatar';
export * from './prismaUserUpdateInputDes';
export * from './prismaUserUpdateInputEmail';
export * from './prismaUserUpdateInputNickname';
export * from './prismaUserUpdateInputPassword';
export * from './prismaUserUpdateInputRole';
export * from './prismaUserUpdateInputUsername';
export * from './repo';
export * from './repoAddFolderBody';
export * from './repoGetParams';
export * from './repoRemoveParams';
export * from './repoUploadFileBody';
export * from './user';
export * from './userGetParams';