/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## xx服务

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */

export * from './apiResponse';
export * from './apiResponseTokenStringMeUser';
export * from './defaultSelectionPrisma36UserPayload';
export * from './jsonResultTypeAny';
export * from './jsonResultTypeTokenStringMeUser';
export * from './jsonResultTypeTokenStringMeUserData';
export * from './loginParams';
export * from './user';