/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 1.0.0
 */
import type { JsonResultTypeTokenStringMeUserData } from './jsonResultTypeTokenStringMeUserData';

export interface JsonResultTypeTokenStringMeUser {
  code: number;
  msg: string;
  data?: JsonResultTypeTokenStringMeUserData;
}
