/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## xx服务

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type JsonResultSuccessTokenStringMeUserCode = typeof JsonResultSuccessTokenStringMeUserCode[keyof typeof JsonResultSuccessTokenStringMeUserCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JsonResultSuccessTokenStringMeUserCode = {
  NUMBER_0: 0,
} as const;
