/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 1.0.0
 */
import type { DefaultSelectionPrisma36UserPayload } from './defaultSelectionPrisma36UserPayload';

export type JsonResultTypeTokenStringMeUserData = {
  me: DefaultSelectionPrisma36UserPayload;
  token: string;
};
