/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Server API
 * ## xx服务

  这是一个基于 Koa + TSOA 的后端 API 服务
 * OpenAPI spec version: 1.0.0
 */
import type { JsonResultSuccessAnyCode } from './jsonResultSuccessAnyCode';

export interface JsonResultSuccessAny {
  /** */
  code: JsonResultSuccessAnyCode;
  msg: string;
  data: unknown;
}
