/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 1.0.0
 */

export interface LoginParams {
  code?: string;
  phone?: string;
  email?: string;
  password?: string;
  account?: string;
}
