/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  JsonResultTypeAny,
  JsonResultTypeTokenStringMeUser,
  LoginParams
} from '../model';





  /**
 * 就是登录接口
 * @summary 登录
 */
export const login = <TData = AxiosResponse<JsonResultTypeTokenStringMeUser>>(
    loginParams: LoginParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/login`,
      loginParams,options
    );
  }
/**
 * 退出登录
 * @summary 退出
 */
export const logout = <TData = AxiosResponse<JsonResultTypeAny>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/logout`,undefined,options
    );
  }
/**
 * 发送证码 接口
 * @summary 发送证码
 */
export const sendCode = <TData = AxiosResponse<JsonResultTypeAny>>(
    sendCodeBody: unknown, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/send-code`,
      sendCodeBody,options
    );
  }
export type LoginResult = AxiosResponse<JsonResultTypeTokenStringMeUser>
export type LogoutResult = AxiosResponse<JsonResultTypeAny>
export type SendCodeResult = AxiosResponse<JsonResultTypeAny>
