/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 1.0.0
 */
import type {
  JsonResultTypeAny,
  JsonResultTypeTokenStringMeUser,
  LoginParams
} from '../model';

import { customAxiosInstance } from '../api.base';




  /**
 * 就是登录接口
 * @summary 登录
 */
export const login = (
    loginParams: LoginParams,
 ) => {
      return customAxiosInstance<JsonResultTypeTokenStringMeUser>(
      {url: `/api/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginParams
    },
      );
    }
  /**
 * 退出登录
 * @summary 退出
 */
export const logout = (
    
 ) => {
      return customAxiosInstance<JsonResultTypeAny>(
      {url: `/api/logout`, method: 'POST'
    },
      );
    }
  /**
 * 发送证码 接口
 * @summary 发送证码
 */
export const sendCode = (
    sendCodeBody: unknown,
 ) => {
      return customAxiosInstance<JsonResultTypeAny>(
      {url: `/api/send-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendCodeBody
    },
      );
    }
  export type LoginResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type LogoutResult = NonNullable<Awaited<ReturnType<typeof logout>>>
export type SendCodeResult = NonNullable<Awaited<ReturnType<typeof sendCode>>>
